import { NextRequest, NextResponse, after } from "next/server";
import { sendEmail } from "@/lib/brevo";
import { getDb, isDbConfigured } from "@/lib/db";
import { getMoonPhaseForDate, getActiveRetrogrades } from "@/lib/ephemeris";
import { makeUnsubscribeToken } from "@/lib/tokens";
import { FALLBACK_QUOTES, LENS_KEYS, type DailyContent, type LensKey } from "@/lib/cosmic-content";
import { isAuthorizedCronRequest, cronAuthHeader } from "@/lib/cron-auth";

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3002";

const LENS_META: Record<LensKey, { icon: string; label: string }> = {
  work: { icon: "💼", label: "Work" },
  love: { icon: "💛", label: "Love" },
  family: { icon: "🏡", label: "Family" },
  money: { icon: "💰", label: "Money" },
  self: { icon: "✨", label: "Self" },
};

// This route only fans out email that content already generated by
// /api/cron/daily-generate. Each invocation claims a bounded batch of
// not-yet-sent subscribers and marks them sent as it goes, so it never has
// to hold the whole subscriber list in one request — it stays fast and
// resumable regardless of how large the list grows. If work remains when
// the batch (or a time budget) runs out, it re-triggers itself in the
// background instead of waiting for tomorrow's cron tick.
const SEND_BATCH_SIZE = 50;
const SEND_TIME_BUDGET_MS = 45_000;
const MAX_CHAIN_DEPTH = 200; // headroom for ~10k subscribers at 50/batch

export const maxDuration = 60;

export async function GET(request: NextRequest) {
  return POST(request);
}

export async function POST(request: NextRequest) {
  if (!isAuthorizedCronRequest(request)) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  if (!isDbConfigured()) {
    return NextResponse.json({ error: "DATABASE_URL not configured" }, { status: 503 });
  }

  const chainDepth = Number(request.nextUrl.searchParams.get("chain") ?? "0");
  const startedAt = Date.now();
  const today = new Date().toISOString().split("T")[0];
  const sql = getDb();
  const moon = getMoonPhaseForDate(today);
  const retro = getActiveRetrogrades(today);

  interface ContentView {
    quote: string;
    subject_line: string | null;
    featured_lens: DailyContent["featured_lens"] | null;
    lenses: DailyContent["lenses"] | null;
  }

  const contentRows = await sql`
    SELECT zodiac_sign, quote, subject_line, featured_lens, lenses FROM daily_quotes WHERE date = ${today}
  `;
  const content: Record<string, ContentView> = {};
  for (const row of contentRows) {
    content[row.zodiac_sign] = {
      quote: row.quote,
      subject_line: row.subject_line,
      featured_lens: row.featured_lens,
      lenses: row.lenses,
    };
  }

  const batch = await sql`
    SELECT id, email, zodiac_sign FROM subscribers
    WHERE confirmed = true AND (last_sent_date IS NULL OR last_sent_date <> ${today})
    ORDER BY id
    LIMIT ${SEND_BATCH_SIZE}
  `;

  let sent = 0;
  let failed = 0;
  let stoppedEarly = false;

  for (const sub of batch) {
    if (Date.now() - startedAt > SEND_TIME_BUDGET_MS) {
      stoppedEarly = true;
      break;
    }

    const signContent = content[sub.zodiac_sign];
    const quote = signContent?.quote ?? FALLBACK_QUOTES[sub.zodiac_sign] ?? FALLBACK_QUOTES["Aries"];
    const subjectLine = signContent?.subject_line ?? `Your ${sub.zodiac_sign} guide for ${today}`;
    const featured = signContent?.featured_lens && signContent.lenses ? signContent.lenses[signContent.featured_lens] : null;
    const featuredMeta = signContent?.featured_lens ? LENS_META[signContent.featured_lens] : null;
    const otherLensLabels = signContent?.featured_lens
      ? LENS_KEYS.filter((k) => k !== signContent.featured_lens).map((k) => LENS_META[k].label)
      : [];

    const unsubToken = makeUnsubscribeToken(sub.email);
    const unsubUrl = `${APP_URL}/api/unsubscribe?email=${encodeURIComponent(sub.email)}&token=${unsubToken}`;

    try {
      const { error } = await sendEmail({
        to: sub.email,
        subject: subjectLine,
        headers: {
          "List-Unsubscribe": `<${unsubUrl}>`,
          "List-Unsubscribe-Post": "List-Unsubscribe=One-Click",
        },
        html: `
          <div style="font-family:Georgia,serif;max-width:480px;margin:0 auto;background:#FAF7F2;color:#2C2420;">
            <!-- Hero image header -->
            <img src="${APP_URL}/hero.jpg" width="480" height="220" alt="" style="width:100%;max-width:480px;height:220px;display:block;object-fit:cover;object-position:center 20%;">
            <!-- Brand -->
            <div style="padding:28px 32px 0;text-align:center;">
              <p style="font-size:11px;color:#B0A090;font-family:sans-serif;letter-spacing:3px;text-transform:uppercase;margin:0 0 6px;">Your daily cosmic guide</p>
              <p style="font-size:20px;font-weight:300;letter-spacing:6px;color:#C9A96E;text-transform:uppercase;margin:0;">Lumora</p>
            </div>
            <!-- Body -->
            <div style="padding:32px 32px 40px;">
              <div style="border-top:1px solid #E8D5B0;margin:0 0 24px;"></div>
              <p style="font-size:11px;color:#B0A090;font-family:sans-serif;letter-spacing:1.5px;text-transform:uppercase;margin:0 0 24px;">${sub.zodiac_sign} · ${moon.phase} in ${moon.sign}${retro ? ` · ${retro}` : ""}</p>
              <p style="font-size:20px;font-style:italic;line-height:1.8;color:#2C2420;margin:0 0 32px;">${quote}</p>
              ${
                featured && featuredMeta
                  ? `
              <div style="border-top:1px solid #E8D5B0;margin:0 0 20px;"></div>
              <p style="font-size:11px;color:#B0A090;font-family:sans-serif;letter-spacing:1.5px;text-transform:uppercase;margin:0 0 10px;">${featuredMeta.icon} Today's focus: ${featuredMeta.label}</p>
              <p style="font-size:15px;line-height:1.6;color:#2C2420;font-family:sans-serif;margin:0 0 20px;">${featured.teaser}</p>
              <p style="font-size:12px;color:#9E7A45;font-family:sans-serif;margin:0 0 28px;">Also today: ${otherLensLabels.join(" · ")} → <a href="${APP_URL}#lenses" style="color:#9E7A45;">See your full guide</a></p>
              `
                  : ""
              }
              <a href="${APP_URL}${featured ? "#lenses" : ""}" style="display:inline-block;border:1.5px solid #C9A96E;color:#C9A96E;text-decoration:none;padding:12px 28px;border-radius:999px;font-size:12px;letter-spacing:2px;font-family:sans-serif;text-transform:uppercase;">Open Lumora</a>
            </div>
            <!-- Footer -->
            <div style="background:#E8E3DA;padding:20px 32px;">
              <p style="font-size:11px;color:#B0A090;font-family:sans-serif;margin:0;"><a href="${unsubUrl}" style="color:#B0A090;">Unsubscribe</a></p>
            </div>
          </div>
        `,
      });

      if (error) throw new Error(error);

      await sql`UPDATE subscribers SET last_sent_date = ${today} WHERE id = ${sub.id}`;
      sent++;
    } catch (err) {
      console.error(`[daily-send] failed to send to ${sub.email}:`, err);
      failed++;
    }
  }

  const [{ remaining }] = await sql`
    SELECT COUNT(*)::int AS remaining FROM subscribers
    WHERE confirmed = true AND (last_sent_date IS NULL OR last_sent_date <> ${today})
  `;

  const shouldChain = remaining > 0 && sent > 0 && chainDepth < MAX_CHAIN_DEPTH;

  if (remaining > 0 && !shouldChain) {
    console.error(
      `[daily-send] stopping with ${remaining} unsent subscribers remaining (sent=${sent}, failed=${failed}, chainDepth=${chainDepth}). Will retry on next scheduled run.`
    );
  }

  if (shouldChain) {
    after(async () => {
      try {
        const res = await fetch(`${APP_URL}/api/cron/daily-send?chain=${chainDepth + 1}`, {
          method: "POST",
          headers: cronAuthHeader(),
        });
        if (!res.ok) {
          console.error(`[daily-send] chained call failed: ${res.status} ${await res.text()}`);
        }
      } catch (err) {
        console.error("[daily-send] failed to trigger next batch:", err);
      }
    });
  }

  return NextResponse.json({
    date: today,
    batch_size: batch.length,
    sent,
    failed,
    remaining,
    stopped_early: stoppedEarly,
    chained: shouldChain,
    chain_depth: chainDepth,
  });
}
